language: java
sudo: true
os:
- linux
jdk:
- oraclejdk8
env:
#   global:
#   # TEST R
#   - secure:
#   - secure:
#    # COVERITY_SCAN_TOKEN
#   - secure:
#   # OSS SONATYPE
#   - secure:
#   - secure:
# matrix:
# - GROUP=1s
# - GROUP=10s
before_install:
#       - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - wget https://downloads.sourceforge.net/project/mpjexpress/releases/mpj-v0_44.zip? -O /tmp/mpj-v0_44.zip
  - unzip /tmp/mpj-v0_44.zip
  - export MPJ_HOME=$PWD/mpj-v0_44/
  - export PATH=$PATH:$MPJ_HOME/bin/
# install:
# - npm install travis-ping
branches:
  only:
  - /^develop.*$/
  - master
  - /^feature.*$/
#  - coverity_scan
notifications:
  email:
    recipients:
    - arnaud.malapert@unice.fr
    on_success: change
    on_failure: always
  # webhooks:
  #   urls:
  #   - https://webhooks.gitter.im/e/26147fbe9b86b606f67d
  #   on_success: change
  #   on_failure: always
  #   on_start: never
# script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mvn clean install -DtestFailureIgnore=true -Dgroups=$GROUP ; fi
# addons:
#   coverity_scan:
#     project:
#       name: "chocoteam/choco-solver"
#       description: "Build submitted via Travis CI"
#     notification_email: choco@emn.fr
#     build_command_prepend: "mvn clean"
#     build_command:   "mvn -DskipTests=true compile"
#     branch_pattern: coverity_scan
#     condition: $GROUP = 1s
# after_success:
# - bash <(curl -s https://codecov.io/bash)
# - travis-ping chocoteam/choco-parsers --branch develop --token ${GH_TOKEN}

# before_deploy:
#   - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
#   - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
# deploy:
#   -
#     provider: script
#     script: /bin/sh ./.travis/deploy.sh
#     skip_cleanup: true
#     on:
#       repo: chocoteam/choco-solver
#       branch: master
#       jdk: oraclejdk8
#       condition: $GROUP = 10s
#   -
#     provider: script
#     script: /bin/sh ./.travis/deploy.sh
#     skip_cleanup: true
#     on:
#       repo: chocoteam/choco-solver
#       tags: true
#       jdk: oraclejdk8
#       condition: $GROUP = 10s
script:
  - mvn verify -B
####
# based on: https://dracoblue.net/dev/uploading-snapshots-and-releases-to-maven-central-with-travis/
####
